### PR TITLE
Updated deprecated calls and fixed relative path 

### PR DESCRIPTION
**Pull request by sebastianhaeni**

### CODE REVIEW

**Comment by kokarn** [comment]
Just FYI, this fixes #40 for me

**Comment by kokarn** [comment]
Sorry, I spoke too soon. 
Fixes the parsing and the panel appearing as it should.

However, after starting a task (etc watch) it still has an overlay that makes it impossible to click anything.

After "Start"
screen shot 2015-03-11 at 13 51 33

After pressing "w"
screen shot 2015-03-11 at 13 51 39

After selecting the task
screen shot 2015-03-11 at 13 50 04

Any chance you can take a look at that as well @sebastianhaeni ?

**Comment by sebastianhaeni** [comment]
@kokarn Did this fix your problem?

**Comment by kokarn** [comment]
@sebastianhaeni Yes! Now it works great again.

Thank you so much and sorry for the late reply.

**Comment by nickclaw** [comment]
Thanks for this!

**Pull request merged**
