### PR TITLE
Fix some deprecation warnings

### PR DESCRIPTION
**Pull request by kokarn**

### CODE REVIEW

**Comment by kokarn** [comment]
This should also fix #28

**Comment by nickclaw** [comment]
Thanks @kokarn, I've noticed you've been pretty active on this project andI don't really have time to maintain it anymore. Would you like to be made a contributor?

**Comment by kokarn** [comment]
Yeah I would love that. 
I have varying amounts of time as well but I can always check PRs and Issues :)

**Comment by nickclaw** [comment]
Awesome, you've been added!

**Comment by kokarn** [comment]
How do you want to handle apm updates? I assume you will do the versions and publish? :)

**Comment by nickclaw** [comment]
Thank you!

Yeah for now just ping me when you increment package.json and I'll publish.

**Comment by kokarn** [comment]
That works for me :)

:+1:

**Pull request merged**
